=== andreasmarkussen/circleci-api/src/types/json/buildAction.schema.json
{
  "$id": "http://circleci.com/api/v1.1",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "body": {
      "$id": "/properties/body",
      "type": "string"
    },
    "branch": {
      "$id": "/properties/branch",
      "type": "string"
    },
    "build_num": {
      "$id": "/properties/build_num",
      "type": "integer"
    },
    "build_time_millis": {
      "$id": "/properties/build_time_millis",
      "type": "integer"
    },
    "build_url": {
      "$id": "/properties/build_url",
      "type": "string"
    },
    "canceled": {
      "$id": "/properties/canceled",
      "type": "boolean"
    },
    "committer_email": {
      "$id": "/properties/committer_email",
      "type": "string"
    },
    "committer_name": {
      "$id": "/properties/committer_name",
      "type": "string"
    },
    "dont_build": {
      "$id": "/properties/dont_build",
      "type": "null"
    },
    "lifecycle": {
      "$id": "/properties/lifecycle",
      "type": "string"
    },
    "outcome": {
      "$id": "/properties/outcome",
      "type": "null"
    },
    "previous": {
      "$id": "/properties/previous",
      "type": "object",
      "properties": {
        "build_num": {
          "$id": "/properties/previous/properties/build_num",
          "type": "integer"
        },
        "status": {
          "$id": "/properties/previous/properties/status",
          "type": "string"
        }
      }
    },
    "queued_at": {
      "$id": "/properties/queued_at",
      "type": "string"
    },
    "reponame": {
      "$id": "/properties/reponame",
      "type": "string"
    },
    "retry_of": {
      "$id": "/properties/retry_of",
      "type": "integer"
    },
    "start_time": {
      "$id": "/properties/start_time",
      "type": "string"
    },
    "status": {
      "$id": "/properties/status",
      "type": "string"
    },
    "stop_time": {
      "$id": "/properties/stop_time",
      "type": "string"
    },
    "subject": {
      "$id": "/properties/subject",
      "type": "string"
    },
    "username": {
      "$id": "/properties/username",
      "type": "string"
    },
    "vcs_revision": {
      "$id": "/properties/vcs_revision",
      "type": "string"
    },
    "vcs_url": {
      "$id": "/properties/vcs_url",
      "type": "string"
    },
    "why": {
      "$id": "/properties/why",
      "type": "string"
    }
  }
}

=== andreasmarkussen/circleci-api/src/types/json/buildAction.sample.json
{
  "body": "",
  "branch": "master",
  "build_num": 23,
  "build_time_millis": 23505,
  "build_url": "https://circleci.com/gh/circleci/mongofinil/23",
  "canceled": false,
  "committer_email": "arohner@gmail.com",
  "committer_name": "Allen Rohner",
  "dont_build": null,
  "lifecycle": "queued",
  "outcome": null,
  "previous": {
    "build_num": 22,
    "status": "failed"
  },
  "queued_at": "2013-04-12T21:33:30Z",
  "reponame": "mongofinil",
  "retry_of": 22,
  "start_time": "2013-04-12T21:33:38Z",
  "status": "queued",
  "stop_time": "2013-04-12T21:34:01Z",
  "subject": "Don't explode when the system clock shifts backwards",
  "username": "circleci",
  "vcs_revision": "1d231626ba1d2838e599c5c598d28e2306ad4e48",
  "vcs_url": "https://github.com/circleci/mongofinil",
  "why": "retry"
}
